
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  inputs:
   command: 'init'
   workingDirectory: '$(System.DefaultWorkingDirectory)/azure-develops-kubernetes'
   commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
   backendType: 'azurerm'
   backendServiceArm: 'azure-resource-manager-service-connection'
   ensureBackend: true
   backendAzureRmResourceGroupName: 'kubernetes'
   backendAzureRmResourceGroupLocation: 'westeurope'
   backendAzureRmStorageAccountName: 'cgtlx2909cgtlx'
   backendAzureRmContainerName: 'cgtlx2909cgtlxcontan'
   backendAzureRmKey: 'kubernetes-dev.tfstate'
