
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendServiceArm: 'AZURE_28'
    backendAzureRmResourceGroupName: 'RGcgtlx'
    backendAzureRmStorageAccountName: 'cgtlx2909cgtlx'
    backendAzureRmContainerName: 'cgtlx2909cgtlxcont'
    backendAzureRmKey: 'kubernetes-cgtlx-dev.tfstste'

